# Kakao map을 이용한 이수 맛집 검색

In [1]:
# BeautifulSoup + Selenium을 같이 조화롭게 코드를 작성
# 왜?
    # selenium은 브라우저 제어 등 자동화에 아주 특화
    # but Selenium 자체로 HTML 파싱, 데이터 추출에 어느정도 한계가 있다.
    # 그렇기 때문에 각자의 장점을 살려서, 짬뽕

In [2]:
# 라이브러리 import

from selenium import webdriver as wb
from bs4 import BeautifulSoup as bs

from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
import time

from tqdm import tqdm

In [3]:
# 브라우저 할당 
driver = wb.Chrome()
driver.get('https://map.kakao.com/')
driver.maximize_window()

In [4]:
# 파란색 팝업 창 기억하는가?
    # 이 부분을 사용자가 클릭해서 없애듯 
    # 컴퓨터에게도 똑같이 시켜줘야한다.
    
click_blue_popup = driver.find_element(By.CSS_SELECTOR,'body > div.coach_layer.coach_layer_type1 > div > div > div > span')
click_blue_popup.click()

In [5]:
# 검색창 지정 (마우스로 올려놓기)

search = driver.find_element(By.CSS_SELECTOR,'#search\.keyword\.query')

# 검색어 입력 ('이수역 맛집')

search.send_keys('이수역 맛집')

# ENTER키 누르고, 데이터가 로드할 수 있는 시간까지 할당해주자

search.send_keys(Keys.ENTER)
time.sleep(3)

### BeautifulSoup 객체화

In [6]:
# 보다 더 빠른 데이터 수집을 위해 -> 추출하는 시간도 이제는 고려

soup = bs(driver.page_source,'lxml')

In [7]:
# 식당이름 (titles)

titles = soup.select('a.link_name')

for i in titles:
    print(i.text)

애플하우스 이수
세녹
스시로로
소담촌 사당직영점
오센
이수회관
호요
전주전집
방배김밥
곱창나라
라화방
호우양꼬치 이수점
훈감동
딥다이브
비엔나커피하우스 이수역점

In [8]:
# 식당 주소 -> addresses

addresses = soup.select('div.addr > p:nth-child(1)')

for i in addresses:
    print(i.text)

서울 동작구 동작대로27다길 29 서광시티뷰 2층 201호
서울 동작구 사당로 304
서울 동작구 동작대로23길 29
서울 동작구 동작대로 43 5층
서울 동작구 동작대로27나길 8
서울 동작구 동작대로27가길 40
서울 동작구 동작대로13길 6-7 1층
서울 동작구 동작대로7길 19
서울 동작구 동작대로27길 59-16
서울 동작구 동작대로27가길 41 1층
서울 동작구 동작대로27길 22
서울 동작구 동작대로27다길 9
서울 동작구 동작대로9길 4 1층
서울 서초구 방배천로18길 36-5 1층
서울 서초구 동작대로 86 1층

In [9]:
# 더보기 버튼 지정 및 클릭

click_more_location = driver.find_element(By.XPATH,'//*[@id="info.search.place.more"]')
click_more_location.click()
time.sleep(2)

In [10]:
# 더보기 버튼을 누른 후에는 , 번호 버튼들이 존재
    # 해당 항목들을 수집

page = driver.find_elements(By.CSS_SELECTOR,'#info\.search\.page > div > a')

### 크롤러 조각하기

In [11]:
# 이제 본격적으로 크롤러를 작성
    # 레고블럭 조립하듯,
    # 버튼, 요소추출 등 필요한 코드를 미리 작성 -> test
    # 반복문으로 만들 때, 이러한 코드들을 
        # 조각조각 붙여넣어보자
        
# Try Except
    # 예외 처리를 위해 
    # 수집을 완료 했거나, 에러가 발생했을 경우, 
        # 에러를 토해내는 것이 아닌,
        # 성공메시지를 에러메시지가 아닌, '수집완료'라는 메시지가 출력되도록 만들기

In [12]:
# 빈 리스트 2개를 생성

titles_list = []
addresses_list = []

try: # 아래 실행코드들을 시도
    while True: # 조건이 참일 경우
        for i in tqdm(range(6)):
            # 0부터 5까지 총 6번 반복
            
            #만약 순차가 5 미만일 경우 
            if (i < 5):
                # 0부터 4까지일때 참,
                # 5번째 페이지 이상일 때, else로 넘어가 다음버튼을 클릭하게됨
                # BeautifulSoup 객체화
                
                page[i].click()
                time.sleep(2)
                
                soup = bs(driver.page_source,'lxml')
                
                # 식당 이름
                titles = soup.select('a.link_name')
                
                # for문을 돌면서 titles에서 순차적으로 
                for i in titles:
                    # titles_list에 순차적으로 뽑은 요소의 텍스트만 넣어줘
                    titles_list.append(i.text)
                
                # 식당 주소
                addresses = soup.select('div.addr > p:nth-child(1)')
                
                # for문을 돌면서 addresses에서 순차적으로 
                for i in addresses:
                    # adresses_list에 순차적으로 뽑은 요소의 텍스트만 넣어줘
                    addresses_list.append(i.text)
            else:
                # 그렇지 않은 경우는,
                # i가 5보다 큰 경우
                # 5번버튼까지 다 돌고, 다음버튼을 눌러야하는 경우
                
                click_next = driver.find_element(By.XPATH,'//*[@id="info.search.page.next"]')
                click_next.click()
                time.sleep(3)
except :
    print('수집이 완료되었습니다.')
    
driver.quit()

100%|████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:13<00:00,  2.33s/it]
100%|████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:13<00:00,  2.33s/it]
100%|████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:13<00:00,  2.32s/it]
100%|████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:13<00:00,  2.33s/it]
100%|████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:13<00:00,  2.31s/it]
100%|████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:13<00:00,  2.33s/it]
 67%|████████████████████████████████████████████████████████                            | 4/6 [00:08<00:04,  2.18s/it]

수집이 완료되었습니다.

In [13]:
titles_list

['애플하우스 이수',
 '세녹',
 '스시로로',
 '소담촌 사당직영점',
 '오센',
 '이수회관',
 '호요',
 '전주전집',
 '방배김밥',
 '곱창나라',
 '라화방',
 '호우양꼬치 이수점',
 '훈감동',
 '딥다이브',
 '비엔나커피하우스 이수역점',
 '삼육가 사당역1호점',
 '신사펍 이수점',
 '이수통닭 본점',
 '낙성곱창',
 '남미플랜트랩',
 '그릴진',
 '디피스트',
 '리에또',
 '단아한정식',
 '청와옥 사당직영점',
 '올라아보 이수본점',
 '초동집 본점',
 '개화',
 '바른식 시골보쌈&감자옹심이 사당역별관점',
 '부엌쟁이',
 '농부쌈밥',
 '리틀크레이지피자',
 '도너츠윤 방배점',
 '강고집 사당본점',
 '유정우함흥냉면',
 '정작가의막걸리집',
 '초와밥',
 '남궁야',
 '갈비연구소',
 '어사출또 이수역점',
 '요란한부엌',
 '월량',
 '조가네갑오징어 사당점',
 '태양커피',
 '쟝블랑제리',
 '가마솥손두부',
 '페니힐스',
 '스타벅스 이수역점',
 '바다해물포차',
 '도어이스케이프 이수역점',
 '주',
 '정담은',
 '도쿄빙수 이수점',
 '구름떡',
 '이수샤브샤브',
 '속초어시장 방배점',
 '다피타시그니처',
 '이수곱창',
 '규스홈 레스토랑',
 '수향가 사당직영점',
 '방배양곱창',
 '양양메밀막국수',
 '마왕족발 이수역점',
 '37.5 동작이수점',
 '샤브리샤브샤브',
 '원조부안집 이수점',
 '머치커피',
 '태양커피 사당점',
 '김재운초밥사랑 이수점',
 '팬쿡 이수점',
 '파니모들',
 '대구형제막창 방배점',
 '여진족',
 '토방소곱창',
 '맥도날드 이수점',
 '한양왕족발',
 '참오리전문점',
 '남성집',
 '용용선생 이수점',
 '정담이깃든사랑채',
 '헬무트',
 '라무진 이수점',
 '김부삼 사당역점',
 '스타벅스 이수역사거리점',
 '인기명 이수점',
 '보태닉마켓',
 '이태리양조장',
 '남해안활어',
 '싱싱오동도 산아나고산꼼장어 숯불구이 이수방배본점',
 '라시에스타',
 '현고대닭발 사당점',
 '정원에프엔비',
 '막걸리학교',
 '수연숯불갈비',
 '미소네',
 '장미맨숀 이수점',
 '구뜰집',
 '오다가다',
 '남도술상',
 '홍미단 방배본점',
 '이고집쭈꾸미 이수점',
 '쿠킨스테이크 이수점',
 '본때 이수점',
 '교대이층집 사당점',
 '한울갈비',
 '순대만드는집',
 '시스트로',
 '용범이네인계동껍데기',
 '코다차야 사당점',
 '크래프트한스 이수점',
 '역전할머니맥주 이수역점',
 '카페오쎄',
 '엔제리너스 이수역점',
 '땡초우동인포차 이수본점',
 '군산 은모래해물탕아구찜 본점',
 '놀란돼지 이수점',
 '고놈들',
 '왕금성 이수역점',
 '올리브에비뉴',
 '모소리 사당점',
 '통영해물보쌈',
 '돈키',
 '요코쵸',
 '언니가 숨겨놓은 과자상자',
 '조개창고 방배점',
 '쇼보 이수점',
 '제줏간 이수점',
 '낯선한식븟다',
 '영풍치킨 사당본점',
 '루키더셰프',
 '오늘와인한잔 이수점',
 '스시코에',
 '호시라멘',
 '천하무족',
 '팔각도 이수역점',
 '해이케이크샵',
 '통영바다풍경 방배1호점',
 '1357철판삼겹',
 '콘크리트',
 '서호김밥 본점',
 '맛찬들왕소금구이 이수점',
 '무삥과팟타이',
 '정원조닭한마리 본점',
 '훈장골 사당점',
 '곽반장',
 '호왕',
 '도쿄하나 사당점',
 '호시',
 '송이하랑',
 '투썸플레이스 이수역사거리점',
 '스시세이',
 '카페페라',
 '차이루',
 '소라노호시',
 '해미수산회정식',
 '24시비사벌 전주콩나물국밥',
 '깔리 사당점',
 '이수명가부대찌개 이수역점',
 '경성모밀',
 '명륜진사갈비 서울사당점',
 '묘오또',
 '김영희강남동태찜 이수점',
 '여정막걸리',
 '이수한우명가',
 '미스피츠',
 '차이797 블랙 서래마을점',
 '복돈이부추삼겹살 사당본점',
 '스타벅스 이수자이점',
 '바른황소곱창',
 '산쪼메 이수점',
 '해물한소반 사당직영점',
 '황토가마솥설렁탕',
 '장수원',
 '영일만',
 '작은피자집',
 '선화의고기 방배본점',
 '명동칼국수',
 '리프레셔스',
 '사당양꼬치',
 '미스사이공 이수점',
 '박은자맛사랑',
 '거북이',
 '로코민트',
 '참숯고깃골',
 '지금보고싶다 이수점',
 '스타벅스 사당역점',
 '경성상회 방배점',
 '모녀당',
 '바르미샤브샤브n칼국수 사당점',
 '책그리고',
 '육갑식당 방배본점',
 '용주골생고기정육식당',
 '럭키갈비찜',
 '외양간',
 '홍두깨손칼국수',
 '정애맛담',
 '이수산더미',
 '바이젠하우스 서울 방배1호점',
 '미구',
 '기꾸참치',
 '흑산도홍탁',
 '메종 엠오 방배본점',
 '권참치 사당점',
 '72420 사당본점',
 '100족발',
 '원조추어탕',
 '고흥이모네전집',
 '군선생 이수역9번출구점',
 '동명 IZAKAYA',
 '여수밤바다',
 '페이브 방배점',
 '맛집부추곱창 사당점',
 '일출횟집',
 '방배반점',
 '아구랜드 방배점',
 '계림닭한마리',
 '고반식당 이수역점',
 '엔터하츠',
 '투썸플레이스 이수역점',
 '릿 잇 타미',
 '솔라스',
 '샘골참숯불막창구이',
 '오늘와인한잔 사당점',
 '할리스 이수역점',
 '하노이별 사당점',
 '남산터 이수점',
 '키친피콜로',
 '북경양꼬치',
 '버거307 이수점',
 '우리황소곱창',
 '7%칠백식당 방배직영점',
 '떡마당떡집',
 '제이콥참치',
 '맛집곱창구이',
 '만화카페쉼표',
 '돼지굴뚝',
 '참치마니아',
 '너땜에한잔',
 '탐나종합어시장 이수역점',
 '리얼양꼬치',
 '심비디움2 사당점',
 '왕돈까스&왕냉면 이수점',
 '김가네칼국수',
 '미사키혼술 이수본점',
 '카페좋아진다',
 '방배한가람김밥',
 '이즈키친',
 '일상다반사',
 '종로곱창',
 '상도늘보리 이수점',
 '마포집',
 '헝그리곰바',
 '이수족발',
 '설빙 이수역점',
 '명성왕족발 남성시장점',
 '광명수산',
 'KFC 이수역점',
 '서울곱창',
 '문어가',
 '일미옥',
 '빈빈양꼬치',
 '품앗이',
 '행복한맥주',
 '신용산감자탕',
 '소문난순대국',
 '당산오돌 사당점',
 '미국식',
 '은연가 사당2호점',
 '진코다리와황태',
 '버거킹 사당역점',
 '원양참치',
 '땡초우동 사당직영2호점',
 '곱분이곱창 이수점',
 '성민양꼬치',
 '용차이',
 '고베그릴',
 '남희회포장마차',
 '롯데리아 이수역점',
 '쩡곱도리탕',
 '고추찜닭 본점',
 '하늘을걷는고양이카페',
 '뚜레쥬르 사당시티점',
 '바다회세꼬시',
 '동래모듬전',
 '베이크샵 피봇',
 '유정오리닭한방백숙',
 '피쉬퓨전회포차 사당점',
 '미분당 이수점',
 '일미가참치',
 '크래프트한스 사당점',
 '등촌샤브칼국수 이수점',
 '이태리상회',
 '메가MGC커피 이수태평점',
 '태평아구찜',
 '남오토코 방배점',
 '힘찬정육식당 사당역직영점',
 '청송산오징어',
 '아는포차',
 '유미카츠 이수방배점',
 '떡붕 이수점',
 '투썸플레이스 방배이수점',
 '겁없는토끼부엌',
 '꿈꾸는크루아상',
 '사당아바이순대국해장국',
 '올웨이즈온',
 '이수면옥',
 '백호양대창 이수점',
 '양계장집아들 방배본점',
 '생고기제작소 이수점',
 '무안수산',
 '포차노리',
 '미고삼',
 '얌리마카롱',
 '이수가',
 '대신수산',
 '홍콩반점0410 이수역점',
 '미테이',
 '어부의딸',
 '도버빌리지',
 '황제소고기국밥',
 '세시파스타',
 '더풍년 이수점',
 '해남원조김밥',
 '키세츠스시',
 '속초오징어어시장 사당점',
 '꽃다운주점 이수점',
 '홍콩참치만두',
 '스타벅스 방배카페거리점',
 '분코',
 '오리촌',
 '조가네족발왕',
 '신전떡볶이 방배점',
 '까르니브라질그릴',
 '전원일기',
 '홍천숯불닭갈비',
 '충청삼겹 이수점',
 '꿈꾸는다락방',
 '토모야',
 '물음표',
 '우리집한우정육식당',
 '슬로우캘리 사당이수점',
 '논고을 사당점',
 '이수정육식당',
 '엘리씨 커피',
 '이수짜장',
 '공평동 꼼장어 이수점',
 '송이족발 본점',
 '에이바우트커피 이수점',
 '천사곱창이수점',
 '꿈꾸는포장마차',
 '제주어항1950',
 '디저트 39',
 '족발의발견',
 '어울림정육식당',
 '탕마루',
 '최고의형제',
 '맘스터치 이수점',
 '남오토코 이수역점',
 'BHC치킨 이수점',
 '힘쎈대머리고창풍천장어',
 '김채원24시감자탕 사당본점',
 '새퍼커피',
 '빽다방 총신대입구역점',
 '이수치막',
 '이수면가 본점',
 '파리바게뜨 이수태평점',
 '청정동해',
 '이디야커피 총신대입구역점',
 '따올라이',
 '비엔나커피하우스 방배점',
 '사당광안리',
 '샌드리아 이수역점',
 '강원도감자탕쌈밥',
 '사당김밥 이수점',
 '나인피스그릴',
 '청년치킨 사당점',
 '전주남부시장콩나물국밥',
 '택이네조개전골 사당점',
 '취향마라 이수역점',
 '미인참치',
 '바오로흑염소농장',
 '오우아',
 '이모네막국수',
 '동대문엽기떡볶이 이수역점',
 '오감쭈꾸미',
 '오봉집 사당점',
 '븟다',
 '경복궁 사당점',
 '이수오뎅 본점',
 '쁘띠우스베이커리',
 '뽕잎사랑 이수점',
 '후지스시',
 '오뎅판다 이수역점',
 '토담골',
 '김봉남포장마차 사당역1호점',
 '종부네',
 '윤공',
 '백미당 서송타워점',
 '스마일포차',
 '돝플러스',
 '철길 부산집 이수점',
 '육감 방배본점',
 '바른치킨 이수역점',
 '쏘맥의달인',
 '담소소사골순대육개장 이수역점',
 '강원도감자옹심이',
 '박가네소문난전집',
 '배스킨라빈스 이수역점',
 '김명자당진동태아구찜탕',
 '금별맥주 이수점',
 '달비촌대구막창',
 '이누식당',
 '달콤커피 이수역점',
 '몰랑이수',
 '돌담',
 '매드포갈릭 사당점',
 '설봄 방배동본점',
 '우리회포차 사당점',
 '남원추어탕',
 '올레요회센터',
 '팬사이',
 '온미정',
 '방배골숯불갈비',
 '바른고기정육점 서래마을본점',
 '성림돼지',
 '장수촌풍천장어직판장',
 '신셰프양꼬치&훠궈 남현동1호점',
 '이수2정육식당',
 '참소예 이수',
 '강릉 교동짬뽕',
 '원당감자탕 사당점',
 '스타벅스 사당로데오점',
 '리요리요커피',
 '백소정 이수역점',
 '시너리(SCENERY)',
 '한앤둘치킨호프 이수역직영점',
 '레코드피맥',
 '블랙모티브 사당역점',
 '흑산도홍어',
 '가가멜식당',
 '신미경의정통춘천닭갈비',
 '야주포차',
 '상아김밥 이수점',
 '바닷가',
 '목포낙지홍어',
 '타누키돈부리 이수역점',
 '금강산감자탕',
 '맛있는뎅',
 '백옥미식성양꼬치마라탕전문점 방배점',
 '메가MGC커피 이수역점',
 '이자카야나무 사당점',
 '찐네빵공장',
 '만랩커피 이수역점',
 '육쌈냉면 이수점',
 '양평해장국',
 '서초면옥 본점',
 'LA부대찌개',
 '만다린',
 '봉평메밀마당 이수역점',
 '탐라포차 이수역점',
 '누룽지통닭굼터',
 '도우룸',
 '정정아식당 이수역점',
 '네꼬',
 '바다당',
 '카페아뜰리에',
 '마초셰프',
 '미스터힐링 이수역점',
 '양모리',
 '푸슈',
 'BBQ 사당점',
 '파아람',
 '바다회센타',
 '이삭토스트 이수역점',
 '조개랑통골뱅이',
 '공차 이수점',
 '이슬도둑',
 '싸다김밥 이수역점',
 '코우엔',
 '명인등심 방배점',
 '향미',
 '이고집쭈꾸미 사당직영점',
 '우탄',
 '경복궁함흥냉면',
 '신채정샤브수끼칼국수',
 '반',
 '아트메이저',
 '꼼 이수본점',
 '브로스키친',
 '정작가의막걸리집 2호점',
 '교촌치킨 사당1호점',
 '강남동태찜',
 '아티제 사당파스텔시티점',
 '일미칼국수',
 '이디야커피 사당점',
 '방배동쌀국수',
 '명동참치',
 '한솥도시락 이수역서문여고점',
 '정겨운늑대',
 '스바루']

In [18]:
len(titles_list),len(addresses_list)

(500, 500)

In [22]:
kakao_data = {'식당 이름' : titles_list, '식당 주소' : addresses_list}
kakao_data

{'식당 이름': ['애플하우스 이수',
  '세녹',
  '스시로로',
  '소담촌 사당직영점',
  '오센',
  '이수회관',
  '호요',
  '전주전집',
  '방배김밥',
  '곱창나라',
  '라화방',
  '호우양꼬치 이수점',
  '훈감동',
  '딥다이브',
  '비엔나커피하우스 이수역점',
  '삼육가 사당역1호점',
  '신사펍 이수점',
  '이수통닭 본점',
  '낙성곱창',
  '남미플랜트랩',
  '그릴진',
  '디피스트',
  '리에또',
  '단아한정식',
  '청와옥 사당직영점',
  '올라아보 이수본점',
  '초동집 본점',
  '개화',
  '바른식 시골보쌈&감자옹심이 사당역별관점',
  '부엌쟁이',
  '농부쌈밥',
  '리틀크레이지피자',
  '도너츠윤 방배점',
  '강고집 사당본점',
  '유정우함흥냉면',
  '정작가의막걸리집',
  '초와밥',
  '남궁야',
  '갈비연구소',
  '어사출또 이수역점',
  '요란한부엌',
  '월량',
  '조가네갑오징어 사당점',
  '태양커피',
  '쟝블랑제리',
  '가마솥손두부',
  '페니힐스',
  '스타벅스 이수역점',
  '바다해물포차',
  '도어이스케이프 이수역점',
  '주',
  '정담은',
  '도쿄빙수 이수점',
  '구름떡',
  '이수샤브샤브',
  '속초어시장 방배점',
  '다피타시그니처',
  '이수곱창',
  '규스홈 레스토랑',
  '수향가 사당직영점',
  '방배양곱창',
  '양양메밀막국수',
  '마왕족발 이수역점',
  '37.5 동작이수점',
  '샤브리샤브샤브',
  '원조부안집 이수점',
  '머치커피',
  '태양커피 사당점',
  '김재운초밥사랑 이수점',
  '팬쿡 이수점',
  '파니모들',
  '대구형제막창 방배점',
  '여진족',
  '토방소곱창',
  '맥도날드 이수점',
  '한양왕족발',
  '참오리전문점',
  '남성집',
  '용용선생 이수점',
  '정담이깃든사랑채',
  '헬무트',
  '라무진 이수점',
  '김부삼 사당역점',
  '스타벅스 이수역사거리점',
  '인기명 이수점',
  '보태닉마켓',
  '이태리양조장',
  '남해안활어',
  '싱싱오동도 산아나고산꼼장어 숯불구이 이수방배본점',
  '라시에스타',
  '현고대닭발 사당점',
  '정원에프엔비',
  '막걸리학교',
  '수연숯불갈비',
  '미소네',
  '장미맨숀 이수점',
  '구뜰집',
  '오다가다',
  '남도술상',
  '홍미단 방배본점',
  '이고집쭈꾸미 이수점',
  '쿠킨스테이크 이수점',
  '본때 이수점',
  '교대이층집 사당점',
  '한울갈비',
  '순대만드는집',
  '시스트로',
  '용범이네인계동껍데기',
  '코다차야 사당점',
  '크래프트한스 이수점',
  '역전할머니맥주 이수역점',
  '카페오쎄',
  '엔제리너스 이수역점',
  '땡초우동인포차 이수본점',
  '군산 은모래해물탕아구찜 본점',
  '놀란돼지 이수점',
  '고놈들',
  '왕금성 이수역점',
  '올리브에비뉴',
  '모소리 사당점',
  '통영해물보쌈',
  '돈키',
  '요코쵸',
  '언니가 숨겨놓은 과자상자',
  '조개창고 방배점',
  '쇼보 이수점',
  '제줏간 이수점',
  '낯선한식븟다',
  '영풍치킨 사당본점',
  '루키더셰프',
  '오늘와인한잔 이수점',
  '스시코에',
  '호시라멘',
  '천하무족',
  '팔각도 이수역점',
  '해이케이크샵',
  '통영바다풍경 방배1호점',
  '1357철판삼겹',
  '콘크리트',
  '서호김밥 본점',
  '맛찬들왕소금구이 이수점',
  '무삥과팟타이',
  '정원조닭한마리 본점',
  '훈장골 사당점',
  '곽반장',
  '호왕',
  '도쿄하나 사당점',
  '호시',
  '송이하랑',
  '투썸플레이스 이수역사거리점',
  '스시세이',
  '카페페라',
  '차이루',
  '소라노호시',
  '해미수산회정식',
  '24시비사벌 전주콩나물국밥',
  '깔리 사당점',
  '이수명가부대찌개 이수역점',
  '경성모밀',
  '명륜진사갈비 서울사당점',
  '묘오또',
  '김영희강남동태찜 이수점',
  '여정막걸리',
  '이수한우명가',
  '미스피츠',
  '차이797 블랙 서래마을점',
  '복돈이부추삼겹살 사당본점',
  '스타벅스 이수자이점',
  '바른황소곱창',
  '산쪼메 이수점',
  '해물한소반 사당직영점',
  '황토가마솥설렁탕',
  '장수원',
  '영일만',
  '작은피자집',
  '선화의고기 방배본점',
  '명동칼국수',
  '리프레셔스',
  '사당양꼬치',
  '미스사이공 이수점',
  '박은자맛사랑',
  '거북이',
  '로코민트',
  '참숯고깃골',
  '지금보고싶다 이수점',
  '스타벅스 사당역점',
  '경성상회 방배점',
  '모녀당',
  '바르미샤브샤브n칼국수 사당점',
  '책그리고',
  '육갑식당 방배본점',
  '용주골생고기정육식당',
  '럭키갈비찜',
  '외양간',
  '홍두깨손칼국수',
  '정애맛담',
  '이수산더미',
  '바이젠하우스 서울 방배1호점',
  '미구',
  '기꾸참치',
  '흑산도홍탁',
  '메종 엠오 방배본점',
  '권참치 사당점',
  '72420 사당본점',
  '100족발',
  '원조추어탕',
  '고흥이모네전집',
  '군선생 이수역9번출구점',
  '동명 IZAKAYA',
  '여수밤바다',
  '페이브 방배점',
  '맛집부추곱창 사당점',
  '일출횟집',
  '방배반점',
  '아구랜드 방배점',
  '계림닭한마리',
  '고반식당 이수역점',
  '엔터하츠',
  '투썸플레이스 이수역점',
  '릿 잇 타미',
  '솔라스',
  '샘골참숯불막창구이',
  '오늘와인한잔 사당점',
  '할리스 이수역점',
  '하노이별 사당점',
  '남산터 이수점',
  '키친피콜로',
  '북경양꼬치',
  '버거307 이수점',
  '우리황소곱창',
  '7%칠백식당 방배직영점',
  '떡마당떡집',
  '제이콥참치',
  '맛집곱창구이',
  '만화카페쉼표',
  '돼지굴뚝',
  '참치마니아',
  '너땜에한잔',
  '탐나종합어시장 이수역점',
  '리얼양꼬치',
  '심비디움2 사당점',
  '왕돈까스&왕냉면 이수점',
  '김가네칼국수',
  '미사키혼술 이수본점',
  '카페좋아진다',
  '방배한가람김밥',
  '이즈키친',
  '일상다반사',
  '종로곱창',
  '상도늘보리 이수점',
  '마포집',
  '헝그리곰바',
  '이수족발',
  '설빙 이수역점',
  '명성왕족발 남성시장점',
  '광명수산',
  'KFC 이수역점',
  '서울곱창',
  '문어가',
  '일미옥',
  '빈빈양꼬치',
  '품앗이',
  '행복한맥주',
  '신용산감자탕',
  '소문난순대국',
  '당산오돌 사당점',
  '미국식',
  '은연가 사당2호점',
  '진코다리와황태',
  '버거킹 사당역점',
  '원양참치',
  '땡초우동 사당직영2호점',
  '곱분이곱창 이수점',
  '성민양꼬치',
  '용차이',
  '고베그릴',
  '남희회포장마차',
  '롯데리아 이수역점',
  '쩡곱도리탕',
  '고추찜닭 본점',
  '하늘을걷는고양이카페',
  '뚜레쥬르 사당시티점',
  '바다회세꼬시',
  '동래모듬전',
  '베이크샵 피봇',
  '유정오리닭한방백숙',
  '피쉬퓨전회포차 사당점',
  '미분당 이수점',
  '일미가참치',
  '크래프트한스 사당점',
  '등촌샤브칼국수 이수점',
  '이태리상회',
  '메가MGC커피 이수태평점',
  '태평아구찜',
  '남오토코 방배점',
  '힘찬정육식당 사당역직영점',
  '청송산오징어',
  '아는포차',
  '유미카츠 이수방배점',
  '떡붕 이수점',
  '투썸플레이스 방배이수점',
  '겁없는토끼부엌',
  '꿈꾸는크루아상',
  '사당아바이순대국해장국',
  '올웨이즈온',
  '이수면옥',
  '백호양대창 이수점',
  '양계장집아들 방배본점',
  '생고기제작소 이수점',
  '무안수산',
  '포차노리',
  '미고삼',
  '얌리마카롱',
  '이수가',
  '대신수산',
  '홍콩반점0410 이수역점',
  '미테이',
  '어부의딸',
  '도버빌리지',
  '황제소고기국밥',
  '세시파스타',
  '더풍년 이수점',
  '해남원조김밥',
  '키세츠스시',
  '속초오징어어시장 사당점',
  '꽃다운주점 이수점',
  '홍콩참치만두',
  '스타벅스 방배카페거리점',
  '분코',
  '오리촌',
  '조가네족발왕',
  '신전떡볶이 방배점',
  '까르니브라질그릴',
  '전원일기',
  '홍천숯불닭갈비',
  '충청삼겹 이수점',
  '꿈꾸는다락방',
  '토모야',
  '물음표',
  '우리집한우정육식당',
  '슬로우캘리 사당이수점',
  '논고을 사당점',
  '이수정육식당',
  '엘리씨 커피',
  '이수짜장',
  '공평동 꼼장어 이수점',
  '송이족발 본점',
  '에이바우트커피 이수점',
  '천사곱창이수점',
  '꿈꾸는포장마차',
  '제주어항1950',
  '디저트 39',
  '족발의발견',
  '어울림정육식당',
  '탕마루',
  '최고의형제',
  '맘스터치 이수점',
  '남오토코 이수역점',
  'BHC치킨 이수점',
  '힘쎈대머리고창풍천장어',
  '김채원24시감자탕 사당본점',
  '새퍼커피',
  '빽다방 총신대입구역점',
  '이수치막',
  '이수면가 본점',
  '파리바게뜨 이수태평점',
  '청정동해',
  '이디야커피 총신대입구역점',
  '따올라이',
  '비엔나커피하우스 방배점',
  '사당광안리',
  '샌드리아 이수역점',
  '강원도감자탕쌈밥',
  '사당김밥 이수점',
  '나인피스그릴',
  '청년치킨 사당점',
  '전주남부시장콩나물국밥',
  '택이네조개전골 사당점',
  '취향마라 이수역점',
  '미인참치',
  '바오로흑염소농장',
  '오우아',
  '이모네막국수',
  '동대문엽기떡볶이 이수역점',
  '오감쭈꾸미',
  '오봉집 사당점',
  '븟다',
  '경복궁 사당점',
  '이수오뎅 본점',
  '쁘띠우스베이커리',
  '뽕잎사랑 이수점',
  '후지스시',
  '오뎅판다 이수역점',
  '토담골',
  '김봉남포장마차 사당역1호점',
  '종부네',
  '윤공',
  '백미당 서송타워점',
  '스마일포차',
  '돝플러스',
  '철길 부산집 이수점',
  '육감 방배본점',
  '바른치킨 이수역점',
  '쏘맥의달인',
  '담소소사골순대육개장 이수역점',
  '강원도감자옹심이',
  '박가네소문난전집',
  '배스킨라빈스 이수역점',
  '김명자당진동태아구찜탕',
  '금별맥주 이수점',
  '달비촌대구막창',
  '이누식당',
  '달콤커피 이수역점',
  '몰랑이수',
  '돌담',
  '매드포갈릭 사당점',
  '설봄 방배동본점',
  '우리회포차 사당점',
  '남원추어탕',
  '올레요회센터',
  '팬사이',
  '온미정',
  '방배골숯불갈비',
  '바른고기정육점 서래마을본점',
  '성림돼지',
  '장수촌풍천장어직판장',
  '신셰프양꼬치&훠궈 남현동1호점',
  '이수2정육식당',
  '참소예 이수',
  '강릉 교동짬뽕',
  '원당감자탕 사당점',
  '스타벅스 사당로데오점',
  '리요리요커피',
  '백소정 이수역점',
  '시너리(SCENERY)',
  '한앤둘치킨호프 이수역직영점',
  '레코드피맥',
  '블랙모티브 사당역점',
  '흑산도홍어',
  '가가멜식당',
  '신미경의정통춘천닭갈비',
  '야주포차',
  '상아김밥 이수점',
  '바닷가',
  '목포낙지홍어',
  '타누키돈부리 이수역점',
  '금강산감자탕',
  '맛있는뎅',
  '백옥미식성양꼬치마라탕전문점 방배점',
  '메가MGC커피 이수역점',
  '이자카야나무 사당점',
  '찐네빵공장',
  '만랩커피 이수역점',
  '육쌈냉면 이수점',
  '양평해장국',
  '서초면옥 본점',
  'LA부대찌개',
  '만다린',
  '봉평메밀마당 이수역점',
  '탐라포차 이수역점',
  '누룽지통닭굼터',
  '도우룸',
  '정정아식당 이수역점',
  '네꼬',
  '바다당',
  '카페아뜰리에',
  '마초셰프',
  '미스터힐링 이수역점',
  '양모리',
  '푸슈',
  'BBQ 사당점',
  '파아람',
  '바다회센타',
  '이삭토스트 이수역점',
  '조개랑통골뱅이',
  '공차 이수점',
  '이슬도둑',
  '싸다김밥 이수역점',
  '코우엔',
  '명인등심 방배점',
  '향미',
  '이고집쭈꾸미 사당직영점',
  '우탄',
  '경복궁함흥냉면',
  '신채정샤브수끼칼국수',
  '반',
  '아트메이저',
  '꼼 이수본점',
  '브로스키친',
  '정작가의막걸리집 2호점',
  '교촌치킨 사당1호점',
  '강남동태찜',
  '아티제 사당파스텔시티점',
  '일미칼국수',
  '이디야커피 사당점',
  '방배동쌀국수',
  '명동참치',
  '한솥도시락 이수역서문여고점',
  '정겨운늑대',
  '스바루'],
 '식당 주소': ['서울 동작구 동작대로27다길 29 서광시티뷰 2층 201호',
  '서울 동작구 사당로 304',
  '서울 동작구 동작대로23길 29',
  '서울 동작구 동작대로 43 5층',
  '서울 동작구 동작대로27나길 8',
  '서울 동작구 동작대로27가길 40',
  '서울 동작구 동작대로13길 6-7 1층',
  '서울 동작구 동작대로7길 19',
  '서울 동작구 동작대로27길 59-16',
  '서울 동작구 동작대로27가길 41 1층',
  '서울 동작구 동작대로27길 22',
  '서울 동작구 동작대로27다길 9',
  '서울 동작구 동작대로9길 4 1층',
  '서울 서초구 방배천로18길 36-5 1층',
  '서울 서초구 동작대로 86 1층',
  '서울 서초구 방배천로 10 1층',
  '서울 동작구 동작대로 129 4층',
  '서울 서초구 방배천로 92 세앙아르비체 102동 107,108호',
  '서울 동작구 동작대로19길 60',
  '서울 서초구 방배천로4안길 55 2층',
  '서울 동작구 동작대로27다길 31 세양그레이스빌 1층 101호',
  '서울 동작구 동작대로27길 31 2층',
  '서울 서초구 방배천로4안길 20 2층',
  '서울 동작구 동작대로27가길 44 2층',
  '서울 동작구 동작대로 71 1층',
  '서울 동작구 사당로 300 이수자이 1층 116호',
  '서울 서초구 방배천로 22',
  '서울 서초구 동작대로 86 동주빌딩 지하 1층',
  '서울 서초구 방배천로 12',
  '서울 동작구 동작대로23길 31',
  '서울 동작구 사당로30길 19',
  '서울 동작구 동작대로27길 9 2층',
  '서울 서초구 동광로12가길 12 1층',
  '서울 서초구 방배천로4안길 6 1층',
  '서울 동작구 동작대로29다길 7-1',
  '서울 동작구 동작대로33가길 5 1층 3호',
  '서울 동작구 동작대로5길 8',
  '서울 서초구 방배천로4안길 10',
  '서울 동작구 동작대로23길 10 1층',
  '서울 동작구 동작대로27나길 21 1층',
  '서울 동작구 사당로30길 126 1층',
  '서울 서초구 서초대로 28 장현빌딩 1층',
  '서울 동작구 남부순환로271길 24',
  '서울 서초구 서초대로25길 55 1층',
  '서울 동작구 동작대로23길 8 1, 2층',
  '서울 동작구 남부순환로271길 20',
  '서울 동작구 동작대로1길 10-14 1,2층',
  '서울 서초구 동작대로 112 한신 휴플러스 1층',
  '서울 서초구 서초대로 20 1층',
  '서울 동작구 동작대로27가길 14 3층',
  '서울 서초구 동광로19길 16',
  '서울 서초구 방배천로2길 15',
  '서울 동작구 동작대로27길 38 1층 103,104호',
  '서울 서초구 방배로33길 21 1층',
  '서울 동작구 동작대로29길 8 2층',
  '서울 서초구 방배천로2길 7 1층',
  '서울 서초구 서초대로 3-4 방배디오슈페리움1 1층 106호',
  '서울 동작구 동작대로27가길 6-4 1층',
  '서울 서초구 방배천로 62 1층',
  '서울 서초구 남부순환로 2121-3',
  '서울 동작구 동작대로23길 27',
  '서울 서초구 동광로15길 10',
  '서울 동작구 동작대로25길 43',
  '서울 동작구 동작대로27가길 23 이오빌딩 2층',
  '서울 서초구 방배천로2길 21 성현빌딩 3층',
  '서울 동작구 동작대로27가길 39 1층',
  '서울 동작구 동작대로9길 43 1층',
  '서울 서초구 방배천로 32 송암빌딩 1층',
  '서울 동작구 동작대로 69 1층',
  '서울 동작구 동작대로27길 34 2층',
  '서울 동작구 동작대로 153 1층',
  '서울 서초구 서초대로 22',
  '서울 서초구 방배천로4안길 12 지하1층,1층',
  '서울 동작구 동작대로7길 11',
  '서울 동작구 사당로 300',
  '서울 서초구 방배천로2안길 15',
  '서울 동작구 사당로 307-10',
  '서울 동작구 동작대로 127 지하1층',
  '서울 동작구 동작대로27다길 26 1층',
  '서울 서초구 방배천로2길 7 2층',
  '서울 서초구 방배천로6길 3-10 1층',
  '서울 동작구 동작대로27길 16-5 1층',
  '서울 서초구 방배천로4길 20 1~3층',
  '서울 서초구 서초대로 3-4',
  '서울 서초구 방배천로 92 109~112호',
  '서울 서초구 방배천로18길 20 1층',
  '서울 동작구 동작대로27가길 26 2층',
  '서울 동작구 사당로30길 157',
  '서울 서초구 서초대로 3-4 방배디오슈페리움1차 103호',
  '서울 동작구 동작대로 21 양지빌딩 6층',
  '서울 동작구 동작대로23길 25',
  '서울 동작구 사당로28길 5 1층',
  '서울 동작구 동작대로25길 41',
  '서울 동작구 동작대로27다길 5 1층',
  '서울 동작구 동작대로7길 32 1층',
  '서울 동작구 동작대로23길 15 1층',
  '서울 서초구 서초대로23길 14 1층',
  '서울 동작구 동작대로35길 10 1층',
  '서울 서초구 방배천로 12-11 지하1층',
  '서울 서초구 효령로31길 94',
  '서울 동작구 동작대로27다길 2 1층',
  '서울 동작구 동작대로27다길 44 2층\xa0',
  '서울 동작구 동작대로27다길 29 1층 103,104호',
  '서울 서초구 방배천로 12-9 2층',
  '서울 동작구 동작대로1길 9 1층',
  '서울 서초구 방배천로8길 6-2',
  '서울 서초구 방배천로24길 25 시현빌 1층 101호',
  '서울 동작구 동작대로25길 22',
  '서울 서초구 방배천로2길 7 지하1층',
  '서울 동작구 동작대로27길 42',
  '서울 동작구 동작대로27다길 26 1층',
  '서울 서초구 방배천로4안길 32 1,2층',
  '서울 동작구 동작대로25길 16',
  '서울 동작구 동작대로27다길 37',
  '서울 서초구 방배천로4길 8',
  '서울 동작구 동작대로17길 6 1층',
  '서울 동작구 동작대로27나길 20 1층',
  '서울 서초구 서초대로 3-4 디오슈페리움 1차 203호',
  '서울 서초구 방배천로 11 파스텔시티 6층',
  '서울 동작구 사당로 243-5 1층',
  '서울 서초구 방배천로4길 26',
  '서울 서초구 방배천로18길 10',
  '서울 동작구 사당로30길 100',
  '서울 서초구 방배천로8길 36 1층',
  '서울 서초구 방배로 147 내방빌딩 3층',
  '서울 동작구 동작대로25길 32 2층',
  '서울 동작구 동작대로27길 22 1층',
  '서울 동작구 사당로30길 28 1층',
  '서울 동작구 동작대로27가길 6',
  '서울 서초구 방배천로16길 18',
  '서울 동작구 동작대로27다길 29 서광시티뷰 1층 101호',
  '서울 서초구 서초대로 17',
  '서울 서초구 방배천로2안길 39 1층',
  '서울 동작구 동작대로7길 74 1층',
  '서울 동작구 동작대로27다길 12 1층',
  '서울 서초구 방배천로2안길 69 1층 103호',
  '서울 서초구 방배천로4안길 55 1층',
  '서울 서초구 방배천로4길 15-17 지하 1층',
  '서울 동작구 동작대로27나길 14',
  '서울 서초구 방배중앙로 141-1',
  '서울 동작구 동작대로27길 16-4 1층',
  '서울 동작구 동작대로27다길 20 2층',
  '서울 동작구 동작대로27다길 11',
  '서울 동작구 동작대로 7 신광빌딩 지하1층',
  '서울 동작구 동작대로27가길 45',
  '서울 서초구 서초대로 91',
  '서울 서초구 방배천로 11 파스텔 시티 3층',
  '서울 서초구 서초대로1길 19-6 1층',
  '서울 서초구 서초대로 21',
  '서울 서초구 서초대로 2 이수파이브 1,2층',
  '서울 동작구 동작대로13길 10 A동 1층',
  '서울 서초구 방배천로 11 1층',
  '서울 동작구 동작대로27길 23 2층',
  '서울 동작구 동작대로27길 16-5 1층',
  '서울 동작구 사당로 295 1층',
  '서울 서초구 동광로10길 2',
  '서울 서초구 방배천로 21 동화빌딩 4층',
  '서울 동작구 동작대로27가길 42',
  '서울 동작구 동작대로29가길 6 1층',
  '서울 동작구 사당로23길 6 1층',
  '서울 서초구 방배로28길 16',
  '서울 서초구 서초대로 3-4 디오슈페리움 1차 지하1층',
  '서울 동작구 동작대로3길 10',
  '서울 동작구 사당로 300 이수자이상가 1층',
  '서울 동작구 동작대로3길 30 1층',
  '서울 서초구 동광로 78 방배빌딩 1,2층',
  '서울 관악구 남현1길 68-14 남현빌딩 1층',
  '서울 동작구 사당로 300',
  '서울 동작구 동작대로7길 4',
  '서울 동작구 사당로 300 이수자이 지하2층 B202호',
  '서울 동작구 동작대로1길 18 1층',
  '서울 동작구 동작대로29가길 8',
  '서울 서초구 방배중앙로 153',
  '서울 동작구 남부순환로271길 27',
  '서울 동작구 사당로30길 96',
  '서울 서초구 서초대로24길 9 1층',
  '서울 서초구 방배천로 12',
  '서울 서초구 청두곶6길 8 1층',
  '서울 동작구 사당로30길 163',
  '서울 서초구 동작대로 108 디오슈페리움2 1층 102호',
  '서울 서초구 방배천로2안길 7 2층',
  '서울 서초구 방배천로4안길 48 1층',
  '서울 서초구 방배천로2안길 48 1층',
  '서울 서초구 방배천로8길 5',
  '서울 동작구 동작대로27가길 26',
  '서울 동작구 동작대로 21 양지빌딩 1~3층',
  '서울 서초구 방배천로 12-3',
  '서울 서초구 방배천로2안길 110 102호',
  '서울 서초구 방배천로 11 파스텔씨티 2층 202-2호',
  '서울 서초구 방배천로 132',
  '서울 서초구 방배중앙로 166 1층',
  '서울 동작구 동작대로17길 5 1층',
  '서울 동작구 사당로29길 2 1층',
  '서울 동작구 동작대로11길 16 1층',
  '서울 동작구 동작대로29나길 10',
  '서울 동작구 동작대로29나길 10 1층',
  '서울 동작구 사당로 307-12 1층',
  '서울 서초구 동작대로 22',
  '서울 서초구 방배천로4길 15-3',
  '서울 동작구 남부순환로271길 14 2층',
  '서울 서초구 방배천로 44',
  '서울 서초구 방배로26길 22 1층',
  '서울 동작구 사당로30길 142 2층',
  '서울 동작구 동작대로1길 50 1층',
  '서울 동작구 사당로30길 154',
  '서울 동작구 동작대로33가길 4',
  '서울 동작구 동작대로7길 24',
  '서울 동작구 동작대로23길 17',
  '서울 관악구 남현1길 42 남현빌딩 4층',
  '서울 동작구 동작대로25길 27 1층',
  '서울 서초구 서초대로25길 32 엠아이빌딩 1층',
  '서울 서초구 방배천로2길 37',
  '서울 서초구 서초대로 30 현진빌딩 1층 1호',
  '서울 서초구 방배천로16길 4 1층',
  '서울 서초구 서초대로 68',
  '서울 동작구 사당로30길 103',
  '서울 동작구 동작대로27가길 15 1층',
  '서울 서초구 동광로 11 빈센트빌딩 1층',
  '서울 동작구 동작대로27길 28 2,3층',
  '서울 서초구 방배천로2안길 31 1층',
  '서울 서초구 방배천로18길 26',
  '서울 서초구 방배천로16길 21',
  '서울 서초구 방배천로4길 15',
  '서울 동작구 동작대로 83 헤라피스빌딩 1층',
  '서울 동작구 사당로30길 97 1층',
  '서울 서초구 동작대로 68 1층',
  '서울 서초구 방배천로4안길 45',
  '서울 동작구 동작대로27길 32 1층',
  '서울 서초구 방배천로18길 16',
  '서울 서초구 방배천로2길 41',
  '서울 서초구 방배로27길 12',
  '서울 서초구 방배로23길 22',
  '서울 동작구 동작대로3길 10 3층',
  '서울 서초구 방배천로2안길 23 1층',
  '서울 동작구 사당로 295 지하1층',
  '서울 동작구 동작대로25길 51',
  '서울 동작구 동작대로7길 12 2층',
  '서울 서초구 방배천로2안길 23',
  '서울 동작구 동작대로 141 1층',
  '서울 동작구 동작대로27길 22 1층',
  '서울 서초구 방배천로 11 5층',
  '서울 동작구 사당로30길 9-1 1층',
  '서울 서초구 서초대로1길 15',
  '서울 동작구 동작대로25길 24 1층',
  '서울 동작구 사당로26길 87 1층',
  '서울 동작구 동작대로7길 55',
  '서울 동작구 동작대로27길 19',
  '서울 동작구 동작대로25길 60-1',
  '서울 동작구 동작대로29길 13',
  '서울 동작구 동작대로31길 3',
  '서울 동작구 동작대로27길 6',
  '서울 서초구 방배천로4안길 61 1층 101호',
  '서울 서초구 방배천로4길 42',
  '서울 동작구 동작대로27가길 12 2층',
  '서울 동작구 동작대로29길 3',
  '서울 동작구 동작대로29가길 5',
  '서울 서초구 동작대로 114 유문빌딩 1층',
  '서울 서초구 방배천로 19 2층',
  '서울 동작구 동작대로27가길 46-5',
  '서울 서초구 서초대로19길 10-21',
  '서울 동작구 남부순환로271길 31',
  '서울 동작구 동작대로27다길 41',
  '서울 동작구 동작대로27길 49',
  '서울 동작구 동작대로23길 17 2층',
  '서울 동작구 동작대로29나길 38',
  '서울 서초구 방배천로4길 18',
  '서울 서초구 동광로24길 50 지니빌 1층',
  '서울 동작구 동작대로23길 31 1층',
  '서울 동작구 동작대로29가길 23-2',
  '서울 동작구 동작대로 21 양지빌딩 1,2층',
  '서울 서초구 방배천로 60',
  '서울 동작구 사당로 280',
  '서울 동작구 동작대로25길 37',
  '서울 서초구 방배천로2길 27',
  '서울 동작구 사당로30길 56 1층',
  '서울 관악구 남부순환로 2082-25 5층',
  '서울 동작구 동작대로27가길 15 1층',
  '서울 동작구 동작대로 129',
  '서울 동작구 사당로30길 140',
  '서울 동작구 동작대로27가길 14',
  '서울 동작구 동작대로27길 15 서범빌딩 4층',
  '서울 동작구 동작대로 79-1 시티빌딩 1층',
  '서울 동작구 동작대로1길 10-16',
  '서울 동작구 동작대로7길 20 동래파전',
  '서울 서초구 방배로23길 5 1층',
  '서울 서초구 방배중앙로 87 1층',
  '서울 동작구 동작대로7길 7',
  '서울 서초구 서초대로 13 마에스트로 1동 107호',
  '서울 동작구 동작대로25길 16 3층',
  '서울 서초구 방배천로 12-4 1층',
  '서울 동작구 사당로 286 2층',
  '서울 동작구 사당로 245 1층',
  '서울 동작구 동작대로27길 20 1층',
  '서울 동작구 사당로 307-14 1층',
  '서울 서초구 방배천로 22',
  '서울 관악구 남현1길 58',
  '서울 관악구 남현1길 8',
  '서울 동작구 동작대로7길 11',
  '서울 동작구 동작대로27길 18 2층',
  '서울 동작구 동작대로29길 57',
  '서울 서초구 서초대로1길 11 1, 2층',
  '서울 서초구 청두곶길 6-1 1층',
  '서울 서초구 서초대로1길 19-6 1층',
  '서울 동작구 사당로 260',
  '서울 서초구 방배천로2안길 45 1층',
  '서울 동작구 동작대로 123',
  '서울 동작구 동작대로25길 30 1층',
  '서울 서초구 방배천로16길 1',
  '서울 동작구 동작대로27다길 6 1층',
  '서울 동작구 동작대로7길 62-1',
  '서울 동작구 동작대로27다길 18 1, 2층',
  '서울 동작구 동작대로27다길 8 1층',
  '서울 서초구 도구로 114',
  '서울 동작구 동작대로27나길 6 2층',
  '서울 동작구 동작대로7길 43 1층',
  '서울 동작구 동작대로27가길 38 1층',
  '서울 서초구 방배중앙로 140',
  '서울 동작구 동작대로25길 9-6',
  '서울 서초구 도구로9길 32 1층',
  '서울 동작구 동작대로29길 11',
  '서울 서초구 효령로 23',
  '서울 동작구 동작대로25길 50 1층',
  '서울 서초구 방배중앙로25길 15',
  '서울 서초구 방배천로4안길 18 1층',
  '서울 관악구 남현1길 47 1,2층',
  '서울 동작구 동작대로27다길 26 이수프라자 1층 105호',
  '서울 동작구 동작대로33길 16',
  '서울 서초구 방배중앙로 162',
  '서울 서초구 방배천로4안길 26',
  '서울 동작구 동작대로31길 13 1층',
  '서울 동작구 동작대로23길 21 대원빌딩 1층',
  '서울 서초구 서초대로1길 19-5 1층',
  '서울 서초구 방배로 83-9 동화빌딩 5층',
  '서울 동작구 동작대로25길 32 1층',
  '서울 동작구 동작대로27가길 41 1층',
  '서울 동작구 동작대로27다길 15 1층',
  '서울 서초구 청두곶길 12 두원아파트상가 1층',
  '서울 서초구 방배천로 17 2층',
  '서울 동작구 동작대로25길 22',
  '서울 동작구 동작대로29가길 9',
  '서울 동작구 사당로 300 이수자이 1층 112호',
  '서울 동작구 남부순환로269길 12',
  '서울 동작구 동작대로27다길 5',
  '서울 서초구 동광로12가길 3',
  '서울 동작구 동작대로29가길 7',
  '서울 동작구 동작대로27가길 6-3',
  '서울 동작구 사당로17길 11',
  '서울 동작구 동작대로27가길 12',
  '서울 동작구 동작대로27다길 29',
  '서울 동작구 동작대로7길 35 1층',
  '서울 서초구 방배로 189 1층',
  '서울 서초구 서초대로 12',
  '서울 동작구 동작대로1길 32 1층',
  '서울 서초구 방배천로2길 25 상원빌딩 1층',
  '서울 동작구 동작대로29가길 10',
  '서울 동작구 동작대로27가길 21 1층',
  '서울 동작구 동작대로27길 15 서범빌딩 2층',
  '서울 동작구 동작대로27다길 42 1층',
  '서울 서초구 서초대로 3-4 디오슈페리움1차 104,104-1호',
  '서울 동작구 동작대로25길 34',
  '서울 동작구 동작대로3길 14',
  '서울 서초구 서초대로4길 17 1층',
  '서울 서초구 동작대로 128 1층',
  '서울 동작구 동작대로27나길 12 1층',
  '서울 서초구 서초대로 3-4 방배디오슈페리움1 1층 102,102-1호',
  '서울 동작구 동작대로27가길 6 백경빌딩 1층 101,102호',
  '서울 서초구 방배천로 40-2',
  '서울 동작구 동작대로 119-1 2층',
  '서울 서초구 방배중앙로 149',
  '서울 서초구 방배로 126 석하빌딩',
  '서울 동작구 동작대로7길 5 1층',
  '서울 서초구 동광로12가길 34',
  '서울 동작구 사당로30길 108',
  '서울 동작구 동작대로25길 40',
  '서울 서초구 방배천로4길 28 연웅빌딩 1층',
  '서울 동작구 사당로30길 96 1층',
  '서울 서초구 방배천로16길 3 1층',
  '서울 동작구 사당로17가길 13 2층',
  '서울 서초구 동작대로 108 디오슈페리움2 1층 105호',
  '서울 서초구 방배천로2길 2',
  '서울 서초구 방배천로 12-9 1층',
  '서울 서초구 방배천로6길 3-4 1층',
  '서울 동작구 동작대로17길 6-4',
  '서울 동작구 사당로 300 125호',
  '서울 서초구 방배천로 12-11 1층',
  '서울 동작구 사당로29길 1 1층',
  '서울 동작구 사당로30길 25 메종슈에뜨이수 1층 102호',
  '서울 서초구 방배천로 11 파스텔시티 602,603호',
  '서울 동작구 동작대로25길 27 1층',
  '서울 동작구 사당로 300 이수자이 104,105,107,108호',
  '서울 동작구 동작대로27가길 22',
  '서울 동작구 동작대로29가길 23 1층',
  '서울 동작구 동작대로27가길 32',
  '서울 동작구 사당로30길 131',
  '서울 동작구 사당로30길 115 2층',
  '서울 동작구 동작대로27가길 37 2층',
  '서울 동작구 동작대로7길 49 1층',
  '서울 동작구 동작대로 137',
  '서울 서초구 방배중앙로 191 1층',
  '서울 서초구 서초대로25길 55 1층',
  '서울 동작구 동작대로27다길 29 서광시티뷰 1층 102호',
  '서울 서초구 효령로 19',
  '서울 동작구 동작대로27다길 14',
  '서울 동작구 동작대로27길 16-6 2층',
  '서울 서초구 서초대로 12 세양아르비채 101동 1층',
  '서울 동작구 사당로30길 63',
  '서울 동작구 동작대로25길 28 1층',
  '서울 동작구 동작대로27길 15 1층 101호',
  '서울 동작구 사당로 229-1',
  '서울 동작구 동작대로27나길 21',
  '서울 동작구 동작대로1길 52',
  '서울 서초구 서초대로27길 33 1층',
  '서울 동작구 동작대로 101 1층',
  '서울 동작구 동작대로29길 24',
  '서울 동작구 동작대로27다길 12 2층',
  '서울 서초구 방배천로 11 파스텔시티 2층',
  '서울 서초구 방배중앙로 172 1층',
  '서울 동작구 사당로30길 148',
  '서울 동작구 동작대로15길 15',
  '서울 동작구 사당로30길 150',
  '서울 동작구 사당로30길 133 2층',
  '서울 동작구 사당로29가길 46 1층',
  '서울 서초구 동광로 7-4 1층',
  '서울 서초구 동광로 80 정암빌딩 1,2층',
  '서울 서초구 서초대로24길 42',
  '서울 관악구 남부순환로 2082-37 2층',
  '서울 관악구 남현3길 71',
  '서울 동작구 동작대로27가길 36 1층',
  '서울 동작구 동작대로27다길 20 1층',
  '서울 서초구 서초대로1길 23 1층',
  '서울 서초구 방배천로4길 9 2,3층',
  '서울 서초구 방배천로 5-4 1~4층',
  '서울 서초구 방배천로18길 11 아르떼상가 B동 104호',
  '서울 동작구 동작대로27길 12 2층',
  '서울 동작구 사당로25가길 1 1층',
  '서울 동작구 동작대로27가길 5',
  '서울 동작구 동작대로27다길 26 1층 101호',
  '서울 동작구 동작대로7길 48 새한빌딩 1층',
  '서울 서초구 방배천로 40-2',
  '서울 동작구 동작대로27다길 11 1층',
  '서울 서초구 방배로16길 11-3',
  '서울 동작구 동작대로7길 7',
  '서울 서초구 서초대로 13 방배마에스트로 1동 1층 103호',
  '서울 동작구 동작대로13길 8 1층',
  '서울 동작구 사당로30길 161',
  '서울 동작구 동작대로27가길 14',
  '서울 동작구 동작대로27길 6',
  '서울 동작구 동작대로7길 21 1층',
  '서울 서초구 방배천로4안길 20',
  '서울 동작구 동작대로 89 골든시네마타워 1층 104호',
  '서울 서초구 방배천로2길 25 2,3층',
  '서울 서초구 방배천로34길 3',
  '서울 서초구 서초대로 13 1동 1층 105호',
  '서울 동작구 동작대로27다길 2',
  '서울 서초구 방배중앙로 64 가이아빌딩 1층',
  '서울 서초구 동광로 97 1층',
  '서울 서초구 효령로31길 90',
  '서울 서초구 방배로23길 13 2층',
  '서울 동작구 동작대로13길 6-3',
  '서울 동작구 동작대로27가길 44 1층',
  '서울 동작구 동작대로31길 5',
  '서울 서초구 동광로 99 2층',
  '서울 서초구 동작대로 108 방배디오슈페리움2차 1층',
  '서울 동작구 사당로30길 133',
  '서울 서초구 방배천로4길 26 2층',
  '서울 서초구 방배천로4길 48 1층',
  '서울 서초구 서초대로25길 8 1층',
  '서울 동작구 동작대로27길 9 5층',
  '서울 서초구 방배로 174 1층',
  '서울 서초구 서초대로19길 10-11 1층',
  '서울 동작구 동작대로9길 7',
  '서울 서초구 동광로12길 120',
  '서울 동작구 동작대로27길 20-7',
  '서울 동작구 동작대로25길 40',
  '서울 동작구 동작대로25길 20',
  '서울 동작구 동작대로27길 14 1층',
  '서울 동작구 동작대로27가길 11 1층',
  '서울 서초구 동작대로 90 인산타워 1층',
  '서울 서초구 방배천로22길 4 방배노블루체서리풀오피스텔 101동 102호',
  '서울 서초구 서초대로 87 1층',
  '서울 서초구 서초대로1길 12',
  '서울 서초구 방배천로2길 39-14',
  '서울 서초구 서초대로1길 8 1층',
  '서울 동작구 동작대로27길 16-7',
  '서울 동작구 동작대로27길 16-7 2층',
  '서울 서초구 서초대로 13 방배마에스트로 지하1층 104호',
  '서울 서초구 서초대로 114 1층',
  '서울 동작구 동작대로27나길 21 두원상가 110,111호',
  '서울 서초구 방배천로18길 32 1층',
  '서울 동작구 동작대로33가길 8',
  '서울 동작구 사당로23길 2 1층',
  '서울 서초구 방배천로2길 31 지상 2층',
  '서울 서초구 방배천로 11 SK리더스뷰',
  '서울 서초구 방배중앙로 167',
  '서울 동작구 동작대로 45',
  '서울 서초구 방배천로8길 34',
  '서울 동작구 동작대로1길 18 2층',
  '서울 서초구 동광로12가길 21',
  '서울 서초구 방배중앙로21길 6',
  '서울 서초구 방배중앙로21길 7 우승빌딩 1층']}

In [23]:
import pandas as pd
kakaos_isu_data = pd.DataFrame(kakao_data)
kakaos_isu_data

              식당 이름                             식당 주소
0          애플하우스 이수  서울 동작구 동작대로27다길 29 서광시티뷰 2층 201호
1                세녹                    서울 동작구 사당로 304
2              스시로로                 서울 동작구 동작대로23길 29
3         소담촌 사당직영점                 서울 동작구 동작대로 43 5층
4                오센                 서울 동작구 동작대로27나길 8
..              ...                               ...
495          방배동쌀국수                  서울 서초구 방배천로8길 34
496            명동참치               서울 동작구 동작대로1길 18 2층
497  한솥도시락 이수역서문여고점                 서울 서초구 동광로12가길 21
498           정겨운늑대                 서울 서초구 방배중앙로21길 6
499             스바루         서울 서초구 방배중앙로21길 7 우승빌딩 1층

[500 rows x 2 columns]

In [24]:
# 크롤링하고 혹여 결과가 중복되게 뽑히는 경우가 있다.
# 물론 코드를 보수하는 방법이 좋지만,
    # 우선 DataFrame으로 뽑아보고,
    # 중복값을 제거해주는 방법도 있다.
    
kakaos_isu_data.drop_duplicates()

              식당 이름                             식당 주소
0          애플하우스 이수  서울 동작구 동작대로27다길 29 서광시티뷰 2층 201호
1                세녹                    서울 동작구 사당로 304
2              스시로로                 서울 동작구 동작대로23길 29
3         소담촌 사당직영점                 서울 동작구 동작대로 43 5층
4                오센                 서울 동작구 동작대로27나길 8
..              ...                               ...
495          방배동쌀국수                  서울 서초구 방배천로8길 34
496            명동참치               서울 동작구 동작대로1길 18 2층
497  한솥도시락 이수역서문여고점                 서울 서초구 동광로12가길 21
498           정겨운늑대                 서울 서초구 방배중앙로21길 6
499             스바루         서울 서초구 방배중앙로21길 7 우승빌딩 1층

[500 rows x 2 columns]

In [27]:
# 파일을 엑셀로 내보내기
kakaos_isu_data.to_excel('C:/Users/user07/Desktop/isu.xlsx',encoding='euc-kr')

C:\Users\user07\anaconda3\lib\site-packages\pandas\util\_decorators.py:211: FutureWarning: the 'encoding' keyword is deprecated and will be removed in a future version. Please take steps to stop the use of 'encoding'
  return func(*args, **kwargs)